Repository adobe/aepsdk-core-android, pull requests merged in 2023-01, with the labels that each got.

#323 Add docs for public services
  docs/Services/Caching.md
  docs/Services/DataQueuing.md
  docs/Services/DataStoring.md
  docs/Services/DeviceInforming.md
  docs/Services/Logging.md
  docs/Services/Networking.md
  docs/Services/README.md
Labels: documentation

#326 Add docs for "Getting started" and "Migration" sections
  docs/GettingStarted.md
  docs/Migration.md
Labels: documentation

#335 [Issue-333] fix a rules engine bug
  code/android-core-library/src/main/java/com/adobe/marketing/mobile/rulesengine/RulesEngine.java
Labels: bug

#355 Ensure initial shared state is created once and sync new ECID immediately after reset
  code/identity/src/main/java/com/adobe/marketing/mobile/identity/IdentityExtension.java
  code/identity/src/test/java/com/adobe/marketing/mobile/identity/IdentityExtensionTests.kt
  code/identity/src/test/java/com/adobe/marketing/mobile/identity/IdentityFunctionalTests.kt
Labels: Identity
